# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75c47b9fb56ec4cac1d003ae045d2af0a81dd54d37de2e52ab036c97dc96a40c791866b20bfec0251b94e7a5829555764a3c08c6a920879b3842cc7a20e7fd2b

test:
  secret_key_base: 738dcffd24b9c68c0044f2f18dfc91886d5135862ef8cb81e7d4abf8eaf46cf2f0aee85d9bd809979e3135e4a6b1ddb6fde0de08bca60ca14e1b6064aa1edf20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 738dcffd24b9c68c0044f2f18dfc91886d5135862ef8cb81e7d4abf8eaf46cf2f0aee85d9bd809979e3135e4a6b1ddb6fde0de08bca60ca14e1b6064aa1eda12
